variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job2:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m unittest discover test "test*.py"

test-printOCR:
  stage: test
  before_script:
    - python print_tests.py
  script:
    - python -m unittest discover test ocr_print.py

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
