variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test-job2:
  stage: test
  before_script:
    - pip install -r requirements.txt
    - python install_nltk.py
  script:
    - python -m unittest discover test "test*.py"

test-printOCR:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m unittest discover test ocr_print.py
